### ISSUE TITLE
hide sidebar button got lost

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#112]
Where did the button go to hide the sidebar?

![Screenshot_20220422-184203~2](https://user-images.githubusercontent.com/15019030/164758139-586de425-3934-4c20-8ae2-35d916410172.png)

**Comment by wellemut** [comment]
@navid-kalaei actually the collapse button is there, you can click it, you just dont see it ;)

**Comment by navid-kalaei** [comment]
the sidebar collapse does not animate correctly on IPhone.

https://user-images.githubusercontent.com/7106251/163857262-cdbdf0d7-723e-4ce5-928d-d328f975437b.mp4

there might be two problems:
1. rc-tween-one is not functioning right.
2. rendering the result cards are heavy so device cannot process them quick and user feels a malfunction

### Edit

1. eliminating rc-tween-one and implementing the collapse transition with pure html and css behaves as intended on the local machine, both in the dev mode and build bundle, but gets corrupted when it lands from the server. the next step is to test [Headless UI](https://headlessui.dev/) . the reason I chose Headless UI is that it's the standard package of Tailwind, and Tailwind is a battle tested reliable framwork.

1. solved in the pure html css. in the Ant documentation there is no Drawer attribute to set style for the content wrapper. hence, setting other styles while useless. that brought me two solutions
   1. to put the button on the map directly and position it the same as the width of drawer + setting the transition speed as it is for the drawer. it worked on local but on the server.
   1. to overwrite the drawer styles from the NextJS styles and place the button inside the drawer (instead of the map). it worked perfectly on Android, IOS, and Desktop



https://user-images.githubusercontent.com/7106251/164894084-aafe3004-8df9-428e-bbbb-ce0c21fb65c1.mp4



### Related Issues
kartevonmorgen/kartevonmorgen#770

**Comment by navid-kalaei** [comment]
the sidebar collapse does not animate correctly on IPhone.

https://user-images.githubusercontent.com/7106251/163857262-cdbdf0d7-723e-4ce5-928d-d328f975437b.mp4

there might be two problems:
1. rc-tween-one is not functioning right.
2. rendering the result cards are heavy so device cannot process them quick and user feels a malfunction

### Edit

1. eliminating rc-tween-one and implementing the collapse transition with pure html and css behaves as intended on the local machine, both in the dev mode and build bundle, but gets corrupted when it lands from the server. the next step is to test [Headless UI](https://headlessui.dev/) . the reason I chose Headless UI is that it's the standard package of Tailwind, and Tailwind is a battle tested reliable framwork.

1. solved in the pure html css. in the Ant documentation there is no Drawer attribute to set style for the content wrapper. hence, setting other styles while useless. that brought me two solutions
   1. to put the button on the map directly and position it the same as the width of drawer + setting the transition speed as it is for the drawer. it worked on local but on the server.
   1. to overwrite the drawer styles from the NextJS styles and place the button inside the drawer (instead of the map). it worked perfectly on Android, IOS, and Desktop



https://user-images.githubusercontent.com/7106251/164894084-aafe3004-8df9-428e-bbbb-ce0c21fb65c1.mp4



### Related Issues
kartevonmorgen/kartevonmorgen#770

**Comment by wellemut** [comment]
Really nice! Its back on track  on live.
![grafik](https://user-images.githubusercontent.com/15019030/165101434-fc2b2d78-358b-4007-bfc1-76f624df0d12.png)

Thank you very much @navid-kalaei !
