### ISSUE TITLE
Make a fallback config-file hard coded

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#208]
**Describe the bug**
The Map App is stopping. One reason could be, that the config file cant get loaded, 
Maybe the config file in the nextcloud  is blocked by nextcloud, because the nextcloud is using/syncing the file.

But that is a bad implementation as an App should not crush completly, just because an API or a config file is not availiabl.

## Solution:
Implement a hard codes version of the config file directly in the App, which gets loaded, if no other config file cant be found in a certain time.

Use the values from the main file for this implementation: https://www.kartevonmorgen.org/public/projects/main/config.json

**To Reproduce**
happens sometimes, you never know when...

**Expected behavior**
stable loading of the map-app. If an API or file is unavalible I expect a popup or an error message.

**Screenshots**
![grafik](https://github.com/kartevonmorgen/kartevonmorgen.ts/assets/15019030/54e72132-a485-4c7d-8932-ade785c8d301)

**Additional context**
The Backend got an update In the beginning of April, so the backend shouldnot be the reason for the bug.
Increasing the timeout is also part of the solution: https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/207

**Comment by navid-kalaei** [comment]
## Summery of the done works

- increased the API call timeout failed
- read the config files directly from the server instead of making the API calls
- if the config file for an specific map does not exist, tries to open the default config
- even if the default config could not be found return the hard coded config
- if for any reasons the json config files are broken, for example syntax error, then return the hard coded config
- for any failure log the error for debugging

# The error messages
- api map config: failed to read config file for project
- api map config: trying to read default config file
- api map config: failed to read default config file
- api map config: failed to parse config file for project

# The hard coded config
```json
{
    "map": {
      "location": {
        "lat": 50.8129,
        "lng": 5.6030,
        "zoom": 6
      },
      "colorStyle": MapColorModes.GRAY
    },
    "popularTags": {
      "min_count": 2
    },
    "sidebar": {
      "title": "Kartevonmorgen"
    }
  }
```

**Comment by wellemut** [comment]
@alex0107 please deplay the realease: https://github.com/kartevonmorgen/kartevonmorgen.ts/releases/tag/v1.2.3

**Comment by wellemut** [comment]
It seems, that all instabilities are solve https://status.rhw24.it/status/allgemein
