### ISSUE TITLE
Automatically update Hashtag-Suggestions

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#50]
On sunday, (3 days ago) I added new entries with the tag: #systemschange

But still, it is not suggested to me, when adding new entries.

- [ ] Make the tags-suggestions-Index to update itself, at least every 5 min.
- [ ] (You do not need to reload all tags. It is sufficient, if you just load the last few page with the little used tags. Use https://kartevonmorgen.org/api/v0/count/tags to see how many tags there are, divide it by 5000 and than call https://kartevonmorgen.org/api/v0/entries/most-popular-tags?min-count=1&offset=9000&limit=1000 to get the ones, that just have been added.

**Comment by navid-kalaei** [comment]
developed on commit cd83ca39a7c71bfe67acfaa3c814517057ac5e3f. for more information of the synchronizer please check the wiki page.

HEADS-UP! there's a bug with [openfairdb](https://github.com/kartevonmorgen/openfairdb/) that returns an empty array when offset is set. [openfairdb#368](https://github.com/kartevonmorgen/openfairdb/issues/386)

**Comment by wellemut** [comment]
Please give me a call, when I can test it on our live-databasis, like https://ssr.kartevonmorgen.org

**Comment by navid-kalaei** [comment]
@wellemut shall we close this issue?

**Comment by wellemut** [comment]
How long does it need, till a newly created hashtag will be suggested?

I created the tag #irantrain and added it to 3 entries: https://dev.kartevonmorgen.org/m/main?c=40.4971%2C6.8115&z=5.00&tag=irantrain
But still, even after reloading, this tag is not suggested, not in the search and not in the tags field of entrys.

In the Wiki it says  `--interval-for-least-used-tags 60`.  But does that mean 60 secons, minuts or days? https://github.com/kartevonmorgen/kartevonmorgen.ts/wiki/How-to-deploy:-tags-synchronizer#how-to-run

**Comment by navid-kalaei** [comment]
the unit is seconds but for the dev purposes I synced the DB just once and stop the continues synchronization. because 1) every time I deploy a new version I almost always forget to run the procedure again. 2) the continues requests takes both network traffic and CPU from the server. the first one can be prevented with an automation service like pm2.config, github action, or other kinds of CI/CD, and for the second reason could you please notify me when you want to test so I can start the script for you?
