### ISSUE TITLE
Old events can not be shown anymore

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kartevonmorgen.ts#71]
## Problem
Users complain, that URLs they have used to promote past events are broken.

Example:  
1.  https://ssr.kartevonmorgen.org/m/main?end_min=1616198400&c=52.4543%2C13.0291&z=10.00&type=event&tag=MehrZusammenGemeinsam
1. https://ssr.kartevonmorgen.org/t/kvm?text=MehrZusammenGemeinsam
1. https://ssr.kartevonmorgen.org/tables/kvm?end_min=1616198400&amp;text=gemeinschaftsgarten&amp;bbox=47.7840960124138,7.522201538085938,48.291873785961066,8.18412780761719
1.  Iframe on https://blog.vonmorgen.org/freiburg/#liste-der-termine
1. Iframe here: https://treffpunkt-freiburg.de/fortbildungen_gemeinschaftsgaerten

All these URLs used to show past events.

**Comment by navid-kalaei** [comment]
I never change the url schema unless we discuss that together. for the urls I have check the network requests from the dev tools, backend sends empty arrays in response. my best guess is that's because of start_min, end_min, or start_max.

related issues are #32 #46 #8
function to parse the time frame from the url is [here](https://github.com/kartevonmorgen/kartevonmorgen.ts/blob/bbc9299aff5a38503f8ceb490f9b6cde7ee7ce5e/utils/router.ts#L92)

**Comment by wellemut** [comment]
unfortunately, I dont know when it was working the last time. But I am sure on 23.09.2021 it was working. But I think that was before our changes in end_min...

**Comment by navid-kalaei** [comment]
yup the problem is with the events time boundaries. here is an example:

source: https://ssr.kartevonmorgen.org/m/main?end_min=1616198400&c=52.4543%2C13.0291&z=10.00&type=event&tag=MehrZusammenGemeinsam
requested api: https://api.ofdb.io/v0/events?bbox=52.21013126818195%2C12.48046875%2C52.697193338145404%2C13.579101562500002&tag=MehrZusammenGemeinsam&start_min=1639427400&end_min=1616198400

converted Unix time to human readable:
 - start_min=Mon Dec 13 2021 20:30:00 GMT+0000
 - end_min=Sat Mar 20 2021 00:00:00 GMT+0000

the start_min is after end_min

**Comment by wellemut** [comment]
yes, that it is the problem. I can hack this, by using both attributes at the same time `start_min=1616198400&end_min=1616198400`
https://dev.kartevonmorgen.org/m/main?start_min=1616198400&end_min=1616198400&c=52.5763%2C12.4667&z=8.00&type=event&tag=MehrZusammenGemeinsam

But i guess we should solve it. Can you fix it?

- [ ] Only If there is no time frame entered by the user, it should always automatically use `end_min=today`
- [ ] But if the user has entered or modified any time box, it should not add a `start_min` or `end_min` attribut to the backend-URL.

And then we soon have to add the time-filters to our map.

**Comment by wellemut** [comment]
@navid-kalaei Would it be more efficient, if we dont care about this bug, and just directly develop this filter menu for time-frames of events? https://github.com/kartevonmorgen/kartevonmorgen/issues/689

Because when we have the filter, you can define, what this filter does...

**Comment by wellemut** [comment]
The events can be easily filtered. really great!
